# Generated by Django 3.0.8 on 2020-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('Glucose', models.FloatField()),
                ('BMI', models.FloatField()),
                ('Age', models.FloatField()),
                ('Diabetesfunction', models.FloatField()),
                ('insulin', models.FloatField()),
            ],
        ),
    ]
